# Generated by Django 4.1.3 on 2022-11-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                default="Developer",
                on_delete=django.db.models.deletion.CASCADE,
                to="task_manager.position",
                to_field="name",
            ),
        ),
    ]
